const PROGRAM=[
{name:'LOWER 1',subtitle:'Deadlift & Quadriceps Focus',ex:[['Conventional Deadlift','Sima Felhúzás','2 × 5–7'],['Hack Squat','Hack Guggolás Gépen','2 × 6–8'],['Leg Extension','Láb Extenzió','2 × 8–10'],['Machine Hip Adduction','Csípő Addukció Gépen','2 × 10–12'],['Standing Calf Raise','Álló Vádli Gépen','2 × 8–10'],['Dumbbell Wrist Curl','Csuklóhajlítás','2 × 12–15'],['Dumbbell Reverse Wrist Curl','Csuklófeszítés','2 × 12–15']]},
{name:'UPPER 1',subtitle:'Chest & Back Thickness',ex:[['Bench Press','Fekvenyomás','2 × 6–8'],['Chest-Supported Row','Mellkassal támasztott Evezés','2 × 6–8'],['Straight-Arm Lat Pulldown','Egyeneskaros Lehúzás','2 × 8–10'],['Lateral Raise','Oldalemelés','2 × 10–12'],['Rear Delt Fly','Hátsó Váll Tárogatás','2 × 10–12'],['Scott Bench Preacher Curl','Scott Pados Bicepsz','2 × 8–10'],['Cable Rope Triceps Pushdown','Csigás Kötél Tricepsz','2 × 8–10']]},
{name:'LOWER 2',subtitle:'Quadriceps, Hamstring & Soleus Focus',ex:[['Smith Machine Bulgarian Split Squat','Smith Bolgár Guggolás','2 × 8–10 / láb'],['Seated Hamstring Curl','Ülő Combhajlítás','2 × 8–10'],['Leg Extension','Láb Extenzió','2 × 10–12'],['Seated Calf Raise','Ülő Vádli Gépen','2 × 10–12'],['Hanging Leg Raise','Függeszkedős Has','2 × 10–12'],['Dumbbell Wrist Curl','Csuklóhajlítás','2 × 12–15'],['Dumbbell Reverse Wrist Curl','Csuklófeszítés','2 × 12–15']]},
{name:'UPPER 2',subtitle:'Shoulders & Lat Width Focus',ex:[['Smith Machine Overhead Shoulder Press','Smith Vállból Nyomás','2 × 6–8'],['Wide-Grip Lat Pulldown','Széles Lehúzás Csigán','2 × 8–10'],['Chest Fly','Mell Tárogatás / Pec Deck','2 × 8–10'],['Cable Face Pull','Face Pull','2 × 10–12'],['Alternating Dumbbell Biceps Curl','Váltott Karú Bicepsz','2 × 8–10'],['Single-Arm Overhead Cable Triceps Extension','1 Kezes Fejfeletti Tricepsz','2 × 8–10']]}
];
const KEY='ironlog-v2'; const OLD='ironlog-v1';
let state=loadState(),timer=null,seconds=150;
function loadState(){try{let x=localStorage.getItem(KEY)||localStorage.getItem(OLD);if(x)return JSON.parse(x)}catch(e){}return{week:1,day:0,logs:{}}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){toast('A böngésző nem engedte a mentést.')}}
function key(w,d,e,s){return `${w}-${d}-${e}-${s}`}
function val(w,d,e,s){return state.logs[key(w,d,e,s)]||{weight:'',reps:'',done:false}}
function prev(w,d,e,s){return w>1?val(w-1,d,e,s):{}}
function renderWeeks(){weekGrid.innerHTML='';for(let w=1;w<=6;w++){let b=document.createElement('button');b.className='week'+(w===state.week?' active':'')+(Object.keys(state.logs).some(k=>k.startsWith(w+'-'))?' done':'');b.textContent=w;b.onclick=()=>{state.week=w;save();render()};weekGrid.appendChild(b)}weekTitle.textContent='WEEK '+state.week}
function renderTabs(){dayTabs.innerHTML='';PROGRAM.forEach((d,i)=>{let b=document.createElement('button');b.className='tab'+(i===state.day?' active':'');b.textContent=d.name;b.onclick=()=>{state.day=i;save();render()};dayTabs.appendChild(b)})}
function renderWorkout(){let d=PROGRAM[state.day],h=`<div class="eyebrow">DAY ${state.day+1} · 2 WORKING SETS / EXERCISE</div><div class="day-name">${d.name}</div><div class="day-meta">${d.subtitle} · Failure / RIR 0–1</div>`;d.ex.forEach((e,i)=>{let p1=prev(state.week,state.day,i,0),p2=prev(state.week,state.day,i,1);h+=`<article class="exercise"><div class="exercise-head"><div><div class="exercise-title">${e[0]}</div><div class="exercise-hu">${e[1]}</div><div class="prescribed">${e[2]}</div></div><div class="eyebrow">#${i+1}</div></div>`;if(p1.weight||p1.reps||p2.weight||p2.reps)h+=`<div class="history"><div>ELŐZŐ HÉT</div><strong>SET 1: ${p1.weight||'—'} kg × ${p1.reps||'—'} · SET 2: ${p2.weight||'—'} kg × ${p2.reps||'—'}</strong></div>`;h+=`<div class="sets"><div class="set-labels"><span>SET</span><span>KG</span><span>REPS</span><span></span></div>`;for(let s=0;s<2;s++){let v=val(state.week,state.day,i,s),p=prev(state.week,state.day,i,s),weight=v.weight!==''?v.weight:(p.weight||''),reps=v.reps!==''?v.reps:(p.reps||'');h+=`<div class="set-row"><div class="set-num">${s+1}</div><input inputmode="decimal" data-t="weight" data-e="${i}" data-s="${s}" value="${weight}" placeholder="kg"><input inputmode="numeric" data-t="reps" data-e="${i}" data-s="${s}" value="${reps}" placeholder="reps"><button class="complete ${v.done?'checked':''}" data-done data-e="${i}" data-s="${s}">${v.done?'✓':'○'}</button></div>`}h+=`</div><div class="last">Pihenő minden lezárt set után: <strong>2:30</strong> · Az előző hét adata automatikusan előtöltve.</div></article>`});h+=`<div class="note">A program rögzített. Csak a saját teljesítményed menthető.</div>`;workout.innerHTML=h;bindInputs()}
function bindInputs(){workout.querySelectorAll('input').forEach(x=>x.oninput=()=>{let e=+x.dataset.e,s=+x.dataset.s,v=val(state.week,state.day,e,s);v[x.dataset.t]=x.value;v.ts=Date.now();state.logs[key(state.week,state.day,e,s)]=v;save()});workout.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>{let e=+b.dataset.e,s=+b.dataset.s,v=val(state.week,state.day,e,s);v.done=!v.done;v.ts=Date.now();state.logs[key(state.week,state.day,e,s)]=v;save();renderWorkout();if(v.done)startTimer(PROGRAM[state.day].ex[e][0])})}
function renderHistory(){let h=`<div class="eyebrow">PROGRESS TRACKER</div><div class="day-name">FEJLŐDÉS</div><div class="day-meta">Minden gyakorlat mindkét setje, hétre bontva.</div>`;PROGRAM.forEach((d,di)=>{h+=`<details class="history-group"><summary>${d.name}</summary>`;d.ex.forEach((e,ei)=>{h+=`<div class="progress-ex"><div class="exercise-title">${e[0]}</div><div class="exercise-hu">${e[1]}</div>`;let any=false;for(let w=1;w<=6;w++){let a=val(w,di,ei,0),b=val(w,di,ei,1);if(a.weight||a.reps||b.weight||b.reps){any=true;h+=`<div class="progress-row"><b>W${w}</b><span>S1: ${a.weight||'—'} kg × ${a.reps||'—'}</span><span>S2: ${b.weight||'—'} kg × ${b.reps||'—'}</span></div>`}}if(!any)h+=`<div class="empty">Még nincs adat.</div>`;h+='</div>'});h+='</details>'});h+=`<div class="note">A napló helyben, ezen az eszközön van mentve.</div>`;workout.innerHTML=h;historyBtn.textContent='← EDZÉS';historyBtn.onclick=render}
function render(){renderWeeks();renderTabs();renderWorkout();ensureHistoryButton()}
function ensureHistoryButton(){let b=document.getElementById('historyBtn');if(!b){b=document.createElement('button');b.id='historyBtn';b.className='ghost';b.textContent='📈 FEJLŐDÉS';document.querySelector('.tabs').after(b);b.onclick=renderHistory}}
function startTimer(ex){seconds=150;timerExercise.textContent=ex+' · következő set';timerOverlay.classList.remove('hidden');updateTimer();clearInterval(timer);timer=setInterval(()=>{seconds--;updateTimer();if(seconds<=0){clearInterval(timer);navigator.vibrate?.([300,150,300]);toast('Pihenő vége — mehet a következő set!');timerOverlay.classList.add('hidden')}},1000)}
function updateTimer(){timerValue.textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0')}
skipTimer.onclick=()=>{clearInterval(timer);timerOverlay.classList.add('hidden')};add30.onclick=()=>{seconds+=30;updateTimer()};function toast(t){let x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove('hidden')});installBtn.onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.classList.add('hidden')}};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
